// <auto-generated />
using System;
using Features.Files;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Features.Migrations
{
    [DbContext(typeof(FileContext))]
    [Migration("20260908011551_fileIntIdToGuidId")]
    partial class fileIntIdToGuidId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Features.Files.BackUpAudit", b =>
                {
                    b.Property<int>("BackUpAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BackUpTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("BackUpAuditId");

                    b.ToTable("BackUpAudits");
                });

            modelBuilder.Entity("Features.Files.BackupFile", b =>
                {
                    b.Property<Guid>("BackUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.HasKey("BackUpId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Features.Files.CopyOptions", b =>
                {
                    b.Property<int>("CopyOptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateParentDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Overwrite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recursive")
                        .HasColumnType("INTEGER");

                    b.HasKey("CopyOptionsId");

                    b.ToTable("CopyOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
